=== lukasbals/code_5_grade/01_Algorithms/src/at/bals/xml/people.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT person (firstname?, lastname, children*)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT children (person)>
<!ATTLIST person id CDATA #REQUIRED>

=== lukasbals/code_5_grade/01_Algorithms/src/at/bals/xml/people1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE person SYSTEM "people.dtd" >
<person id="1">
	<firstname>Lukas</firstname>
	<lastname>Bals</lastname>
	<children>
		<person id="2">
			<firstname>Timo</firstname>
			<lastname>Bals</lastname>
		</person>
	</children>
	<children>
		<person id="3">
			<firstname>Brigitte</firstname>
			<lastname>Bals</lastname>
		</person>
	</children>
</person>
